export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const FILTRAR_PRODUCTOS_ORDEN = "FILTRAR_PRODUCTOS_ORDEN";
export const FILTRAR_PRODUCTOS_CONDICION = "FILTRAR_PRODUCTOS_CONDICION";
export const FILTRAR_PRODUCTOS_POR_CANTIDAD = "FILTRAR_PRODUCTOS_POR_CANTIDAD";
